// Fuente declarativa del seed de la Demo (PRD §10 + spec acceso §4).
// Cubren los casos difíciles: `resolvedBy: 'heuristic'` sin componente ni ruta,
// una entrada con `snapshotStatus: 'failed'`, un viewport móvil y una sesión `open`.
//
// Los snapshots de `public/mock/` son rrweb-snapshot REALES, serializados de
// `public/mock/screen-1.html` (1440 × 900) y `public/mock/screen-3.html` (390 × 844).
// Los `rect` / `boxModel` de abajo están MEDIDOS sobre esos documentos, así que los
// marcadores del viewer caen exactamente encima del elemento anotado. Si se editan
// esos HTML hay que volver a medir.

import type { Session } from '@punto/contracts'

export const demoSessionFixture: Session = {
  id: 'ses_1',
  publicId: 'AbC123XyZ456DeF789GhJ0',
  projectName: 'Armot',
  title: 'Review de Insumos — 17 ago',
  status: 'closed',
  createdAt: '2026-08-17T15:02:00.000Z',
  closedAt: '2026-08-17T15:41:00.000Z',
  entries: [
    {
      id: 'ent_1',
      order: 1,
      url: 'https://armot.local/insumos/nuevo',
      pageTitle: 'Nuevo insumo · Armot',
      viewport: { width: 1440, height: 900, dpr: 2 },
      snapshotUrl: '/mock/snapshot-1.json',
      thumbnailUrl: '/mock/snapshot-1.webp',
      snapshotStatus: 'ready',
      capturedAt: '2026-08-17T15:04:00.000Z',
      annotations: [
        {
          id: 'ann_1',
          number: 1,
          body: 'El botón queda muy pegado al borde inferior. Debería respirar al menos 24px.',
          createdAt: '2026-08-17T15:03:40.000Z',
          target: {
            selector: 'main > form > button.px-4',
            nodeId: 412,
            rect: { x: 1071, y: 652, w: 96, h: 40 },
            boxModel: {
              content: { x: 1071, y: 652, w: 96, h: 40 },
              padding: { top: 8, right: 16, bottom: 8, left: 16 },
              border: { top: 1, right: 1, bottom: 1, left: 1 },
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
            },
            tag: 'button',
            text: 'Guardar',
            component: 'PrimaryButton',
            componentStack: ['NuevoInsumoPage', 'InsumoForm', 'PrimaryButton'],
            source: 'src/components/PrimaryButton.tsx:24',
            resolvedBy: 'fiber-source',
          },
        },
        {
          // resolvedBy 'heuristic', sin component ni source → la UI no debe romperse.
          id: 'ann_2',
          number: 2,
          body: 'Esta etiqueta dice “Cant.” y en el resto del formulario decimos “Cantidad”. Falta consistencia.',
          createdAt: '2026-08-17T15:05:12.000Z',
          target: {
            selector: 'main > form > div:nth-child(3) > label',
            nodeId: 388,
            rect: { x: 353, y: 379, w: 36, h: 21 },
            boxModel: {
              content: { x: 353, y: 379, w: 36, h: 21 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              border: { top: 0, right: 0, bottom: 0, left: 0 },
              margin: { top: 0, right: 0, bottom: 4, left: 0 },
            },
            tag: 'label',
            text: 'Cant.',
            resolvedBy: 'heuristic',
          },
        },
        {
          id: 'ann_3',
          number: 3,
          body: 'El input de precio acepta letras. Debería ser numérico y alinear a la derecha.',
          createdAt: '2026-08-17T15:06:03.000Z',
          target: {
            selector: 'main > form > div:nth-child(4) > input#precio',
            nodeId: 401,
            rect: { x: 353, y: 485, w: 280, h: 40 },
            boxModel: {
              content: { x: 353, y: 485, w: 280, h: 40 },
              padding: { top: 10, right: 12, bottom: 10, left: 12 },
              border: { top: 1, right: 1, bottom: 1, left: 1 },
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
            },
            tag: 'input',
            text: '',
            component: 'MoneyInput',
            componentStack: ['NuevoInsumoPage', 'InsumoForm', 'Field', 'MoneyInput'],
            resolvedBy: 'fiber',
          },
        },
      ],
    },
    {
      // snapshotStatus 'failed': se muestra el bloque de fallo y sus comentarios igual.
      id: 'ent_2',
      order: 2,
      url: 'https://armot.local/insumos',
      pageTitle: 'Insumos · Armot',
      viewport: { width: 1440, height: 900, dpr: 2 },
      snapshotUrl: null,
      thumbnailUrl: null,
      snapshotStatus: 'failed',
      capturedAt: '2026-08-17T15:18:00.000Z',
      annotations: [
        {
          id: 'ann_4',
          number: 1,
          body: 'La tabla no tiene estado vacío: cuando no hay insumos solo se ve el encabezado.',
          createdAt: '2026-08-17T15:17:20.000Z',
          target: {
            selector: 'main > section > table > tbody',
            nodeId: 214,
            rect: { x: 240, y: 300, w: 960, h: 48 },
            boxModel: {
              content: { x: 240, y: 300, w: 960, h: 48 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              border: { top: 0, right: 0, bottom: 1, left: 0 },
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
            },
            tag: 'tbody',
            text: '',
            component: 'InsumosTable',
            componentStack: ['InsumosPage', 'InsumosTable'],
            source: 'src/components/InsumosTable.tsx:57',
            resolvedBy: 'fiber-source',
          },
        },
        {
          id: 'ann_5',
          number: 2,
          body: 'El buscador pierde el foco al escribir la primera letra; se está remontando en cada tecla.',
          createdAt: '2026-08-17T15:19:44.000Z',
          target: {
            selector: 'header > form > input[type="search"]',
            nodeId: 128,
            rect: { x: 240, y: 196, w: 320, h: 36 },
            boxModel: {
              content: { x: 240, y: 196, w: 320, h: 36 },
              padding: { top: 8, right: 12, bottom: 8, left: 36 },
              border: { top: 1, right: 1, bottom: 1, left: 1 },
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
            },
            tag: 'input',
            text: '',
            resolvedBy: 'heuristic',
          },
        },
      ],
    },
    {
      // Viewport móvil 390 × 844 → probar el escalado.
      id: 'ent_3',
      order: 3,
      url: 'https://armot.local/insumos/nuevo?m=1',
      pageTitle: 'Nuevo insumo · Armot',
      viewport: { width: 390, height: 844, dpr: 3 },
      snapshotUrl: '/mock/snapshot-3.json',
      thumbnailUrl: '/mock/snapshot-3.webp',
      snapshotStatus: 'ready',
      capturedAt: '2026-08-17T15:33:00.000Z',
      annotations: [
        {
          id: 'ann_6',
          number: 1,
          body: 'En móvil el botón de guardar tapa el último campo. Debería ir en una barra fija con padding.',
          createdAt: '2026-08-17T15:32:10.000Z',
          target: {
            selector: 'main > form > button.px-4',
            nodeId: 412,
            rect: { x: 16, y: 531, w: 358, h: 48 },
            boxModel: {
              content: { x: 16, y: 531, w: 358, h: 48 },
              padding: { top: 12, right: 16, bottom: 12, left: 16 },
              border: { top: 1, right: 1, bottom: 1, left: 1 },
              margin: { top: 8, right: 0, bottom: 8, left: 0 },
            },
            tag: 'button',
            text: 'Guardar cambios',
            component: 'PrimaryButton',
            componentStack: ['NuevoInsumoPage', 'InsumoForm', 'PrimaryButton'],
            source: 'src/components/PrimaryButton.tsx:24',
            resolvedBy: 'fiber-source',
          },
        },
        {
          id: 'ann_7',
          number: 2,
          body: 'El título se corta en dos líneas y queda muy junto al botón de regresar.',
          createdAt: '2026-08-17T15:33:28.000Z',
          target: {
            selector: 'header > h1',
            nodeId: 96,
            rect: { x: 56, y: 24, w: 230, h: 56 },
            boxModel: {
              content: { x: 56, y: 24, w: 230, h: 56 },
              padding: { top: 0, right: 0, bottom: 0, left: 0 },
              border: { top: 0, right: 0, bottom: 0, left: 0 },
              margin: { top: 0, right: 0, bottom: 12, left: 0 },
            },
            tag: 'h1',
            text: 'Nuevo insumo de inventario',
            component: 'PageTitle',
            componentStack: ['NuevoInsumoPage', 'PageHeader', 'PageTitle'],
            resolvedBy: 'fiber',
          },
        },
        {
          id: 'ann_8',
          number: 3,
          body: 'El select de unidad abre el teclado nativo encima del campo y no se ve lo seleccionado.',
          createdAt: '2026-08-17T15:34:02.000Z',
          target: {
            selector: 'main > form > div:nth-child(2) > select',
            nodeId: 271,
            rect: { x: 16, y: 238, w: 358, h: 44 },
            boxModel: {
              content: { x: 16, y: 238, w: 358, h: 44 },
              padding: { top: 10, right: 32, bottom: 10, left: 12 },
              border: { top: 1, right: 1, bottom: 1, left: 1 },
              margin: { top: 0, right: 0, bottom: 0, left: 0 },
            },
            tag: 'select',
            text: 'Kilogramo',
            resolvedBy: 'heuristic',
          },
        },
        {
          id: 'ann_9',
          number: 4,
          body: 'Los chips de categoría se salen del ancho y provocan scroll horizontal en 390.',
          createdAt: '2026-08-17T15:35:47.000Z',
          target: {
            selector: 'main > form > div.chips',
            nodeId: 305,
            rect: { x: 16, y: 475, w: 374, h: 32 },
            boxModel: {
              content: { x: 16, y: 475, w: 374, h: 32 },
              padding: { top: 4, right: 8, bottom: 4, left: 8 },
              border: { top: 0, right: 0, bottom: 0, left: 0 },
              margin: { top: 0, right: 0, bottom: 24, left: 0 },
            },
            tag: 'div',
            text: 'Abarrotes Lácteos Limpieza Empaque',
            component: 'CategoryChips',
            componentStack: ['NuevoInsumoPage', 'InsumoForm', 'CategoryChips'],
            source: 'src/components/CategoryChips.tsx:12',
            resolvedBy: 'fiber-source',
          },
        },
      ],
    },
  ],
}
